BasketTask/BasketTask/Models/Categories.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasketTask.Models
{
    public class Categories
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<CategoryProducts> CategoryProducts { get; set; }
    }
}

BasketTask/BasketTask/Models/CategoryProducts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasketTask.Models
{
    public class CategoryProducts
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Categories Categories { get; set; }
        public int CategoriesId { get; set; }
    }
}

BasketTask/BasketTask/Models/Settings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasketTask.Models
{
    public class Settings
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    }
}

BasketTask/BasketTask/Models/Slider.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasketTask.Models
{
    public class Slider
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public List<SliderImage> Images { get; set; }
    }
}

BasketTask/BasketTask/Models/SliderImage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasketTask.Models
{
    public class SliderImage
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public bool IsMain { get; set; }
        public Slider Slider { get; set; }
        public int SliderId { get; set; }
    }
}

BasketTask/BasketTask/ViewModels/HomeVM.cs
using BasketTask.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasketTask.ViewModels
{
    public class HomeVM
    {
        public List<Slider> Sliders { get; set; }
        public SliderImage SliderImage { get; set; }
    }
}

BasketTask/BasketTask/ViewModels/LayoutVM.cs
using BasketTask.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasketTask.ViewModels
{
    public class LayoutVM
    {
        public List<Categories> Categories { get; set; }
        public List<CategoryProducts> CategoryProducts { get; set; }
        public Dictionary<string, string> Settings { get; set; }
    }
}

BasketTask/BasketTask/Controllers/HomeController.cs
using BasketTask.Data;
using BasketTask.Models;
using BasketTask.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasketTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;
        public HomeController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Slider> sliders = await _context.Sliders.Include(i=>i.Images).ToListAsync();
            SliderImage sliderImage = await _context.SliderImages.FirstOrDefaultAsync();
            

            HomeVM homeVM = new HomeVM
            {
                Sliders = sliders,
                SliderImage = sliderImage,
            };

            return View(homeVM);
        }
    }
}

BasketTask/BasketTask/ViewComponents/FooterViewComponent.cs
using BasketTask.Data;
using BasketTask.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasketTask.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        private readonly AppDbContext _context;
        private readonly LayoutService _layoutService;
        public FooterViewComponent(LayoutService layoutService, AppDbContext context)
        {
            _layoutService = layoutService;
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            Dictionary<string, string> settings = _layoutService.GetSetting();

            return (await Task.FromResult(View(settings)));
        }

    }
}

BasketTask/BasketTask/ViewComponents/HeaderViewComponent.cs
using BasketTask.Data;
using BasketTask.Models;
using BasketTask.Services;
using BasketTask.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasketTask.ViewComponents
{
    public class HeaderViewComponent: ViewComponent
    {
        private readonly AppDbContext _context;
        private readonly LayoutService _layoutService;
        public HeaderViewComponent(LayoutService layoutService, AppDbContext context)
        {
            _layoutService = layoutService;
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            

            Dictionary<string, string> settings = _layoutService.GetSetting();
            List<Categories> categories = await _context.Categories.Include(i => i.CategoryProducts).ToListAsync();
            List<CategoryProducts> categoryProducts = await _context.CategoryProducts.ToListAsync();

            LayoutVM layoutVM = new LayoutVM
            {
                Categories = categories,
                CategoryProducts = categoryProducts,
                Settings = settings
            };

            return (await Task.FromResult(View(layoutVM))); 
        }
    }
}

BasketTask/BasketTask/Views/Shared/Components/Footer/Default.cshtml
@model Dictionary<string, string>

<footer>
    <section id="subscribe">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-12">
                    <div class="subscribe-content">
                        <h6>$20 discount to your first order</h6>
                        <h3>Join our newsletter and get...</h3>
                        <p>Join our email subscription now to get updates<br>on promotions and coupons.</p>
                        <div class="email">
                            <i class="fa-solid fa-envelope"></i><input type="email"
                                                                       placeholder="Your email address"><button type="submit">Subscribe</button>
                        </div>
                    </div>
                </div>
                <div class="col-xl-7 d-xs-none d-md-none d-xl-block">
                    <div class="subscribe-img">
                        <img src="https://klbtheme.com/bacola/wp-content/uploads/2021/04/coupon.png"
                             alt="subscribe">
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="iconboxes" class="pt-5">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-6">
                    <div class="content">
                        <i class="fas fa-prescription-bottle"></i> Everyday fresh products
                    </div>
                </div>
                <div class="col-xl-3 col-6">
                    <div class="content">
                        <i class="fas fa-truck"></i> Free delivery for order over $70
                    </div>
                </div>
                <div class="col-xl-3 col-6">
                    <div class="content">
                        <i class="fas fa-percent"></i> Daily Mega Discounts
                    </div>
                </div>
                <div class="col-xl-3 col-6">
                    <div class="content">
                        <i class="fas fa-dollar-sign"></i> Best price on the mark
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="widgets" class="pt-5">
        <div class="container">
            <hr>
            <div class="row justify-content-between pt-5 pb-5">
                <div class="col-xl-2 col-4">
                    <div class="content">
                        <h4>FRUIT & VEGETABLES</h4>
                        <div class="links">
                            <a href="">Fresh Vegetables</a><br>
                            <a href="">Herbs & Seasonings</a><br>
                            <a href="">Fresh Fruits</a><br>
                            <a href="">Cuts & Sprouts</a><br>
                            <a href="">Exotic Fruits & Veggie</a><br>
                            <a href="">Packaged Produce</a><br>
                            <a href="">Party Trays</a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 col-4">
                    <div class="content">
                        <h4>BREAKFAST & DAIRY</h4>
                        <div class="links">
                            <a href="">Milk & Flavoured Milk</a><br>
                            <a href="">Butter and Margarine</a><br>
                            <a href="">Cheese</a><br>
                            <a href="">Eggs</a><br>
                            <a href="">Honey</a><br>
                            <a href="">Marmalades</a><br>
                            <a href="">Sour Cream and Dips</a><br>
                            <a href="">Yogurt Substitutes</a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 col-4">
                    <div class="content">
                        <h4>MEAT & SEAFOOD</h4>
                        <div class="links">
                            <a href="">Breakfast Sausage</a><br>
                            <a href="">Dinner Sausage</a><br>
                            <a href="">Beef</a><br>
                            <a href="">Chichken</a><br>
                            <a href="">Sliced Deli Meat</a><br>
                            <a href="">Shrimp</a><br>
                            <a href="">Wild Caught Fillets</a><br>
                            <a href="">Crab and Shellfish</a><br>
                            <a href="">Farm Raised Fillets</a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 col-4">
                    <div class="content">
                        <h4>BEVERAGES</h4>
                        <div class="links">
                            <a href="">Water</a><br>
                            <a href="">Sparkling Water</a><br>
                            <a href="">Soda & Pop</a><br>
                            <a href="">Coffee</a><br>
                            <a href="">Milk & Plant-Based Milk</a><br>
                            <a href="">Tea & Kombucha</a><br>
                            <a href="">Drink Boxes & Pouches</a><br>
                            <a href="">Craft Beer</a><br>
                            <a href="">Wine</a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 col-4">
                    <div class="content">
                        <h4>BREADS & BAKERY</h4>
                        <div class="links">
                            <a href="">Milk & Flavoured Milk</a><br>
                            <a href="">Butter and Margarine</a><br>
                            <a href="">Cheese</a><br>
                            <a href="">Eggs Substitutes</a><br>
                            <a href="">Honey</a><br>
                            <a href="">Marmalades</a><br>
                            <a href="">Sour Cream and Dips</a><br>
                            <a href="">Yogurt</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="contact" class="mt-5">
        <div class="container">
            <div class="row">
                <div class="col-6 d-flex">
                    <div class="icon"><i class="fas fa-phone"></i></div>
                    <div class="info">
                        <h4>@Model["FooterPhone"]</h4>
                        <span>Working 8:00 - 22:00</span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="row">
                        <div class="col-10">
                            <div class="mobile-app d-flex">
                                <div class="app-contents">
                                    <h6>Download App on Mobile :</h6>
                                    <span>15% discount on your first purchase</span>
                                </div>
                                <div class="app-buttons d-flex">
                                    <a href="https://play.google.com/store">
                                        <img src="https://klbtheme.com/bacola/wp-content/uploads/2021/04/google-play.png"
                                             alt="app">
                                    </a>
                                    <a href="https://www.apple.com/app-store/">
                                        <img src="https://klbtheme.com/bacola/wp-content/uploads/2021/04/app-store.png"
                                             alt="app">
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="site-local">
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fa-brands fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr>

        </div>
    </section>
</footer>

BasketTask/BasketTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bacola</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="~/assets/css/flipclock.css">
    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/assets/css/home.css">
</head>

<body class="mb-5">
    @await Component.InvokeAsync("Header");

    @RenderBody()

    @await Component.InvokeAsync("Footer");

    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.10.2/dist/umd/popper.min.js"
            integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
            integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"
            integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2"
            crossorigin="anonymous"></script>
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/flipclock.min.js"></script>
    <script src="~/assets/js/home.js"></script>
</body>

</html>